name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # ajusta conforme necessário

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies and build
        run: |
          npm install -g @quasar/cli
          npm install
          quasar build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/spa  # ajusta o diretório conforme o output do quasar build
          publish_branch: gh-pages
          force_orphan: true  # opcional, para recriar a branch gh-pages

